#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : rubygem-sass-rails
Version  : 5.0.4
Release  : 4
URL      : https://rubygems.org/downloads/sass-rails-5.0.4.gem
Source0  : https://rubygems.org/downloads/sass-rails-5.0.4.gem
Summary  : No detailed summary available
Group    : Development/Tools
License  : MIT
BuildRequires : ruby
BuildRequires : rubygem-rdoc
BuildRequires : rubygem-sqlite3

%description
# Official Ruby-on-Rails Integration with Sass
This gem provides official integration for Ruby on Rails projects with the Sass stylesheet language.

%prep
gem unpack %{SOURCE0}
%setup -q -D -T -n sass-rails-5.0.4
gem spec %{SOURCE0} -l --ruby > rubygem-sass-rails.gemspec

%build
gem build rubygem-sass-rails.gemspec

%install
%global gem_dir $(ruby -e'puts Gem.default_dir')
gem install -V \
--local \
--force \
--install-dir .%{gem_dir} \
--bindir .%{_bindir} \
sass-rails-5.0.4.gem

mkdir -p %{buildroot}%{gem_dir}
cp -pa .%{gem_dir}/* \
%{buildroot}%{gem_dir}

if [ -d .%{_bindir} ]; then
mkdir -p %{buildroot}%{_bindir}
cp -pa .%{_bindir}/* \
%{buildroot}%{_bindir}/
fi


%files
%defattr(-,root,root,-)
/usr/lib64/ruby/gems/2.3.0/cache/sass-rails-5.0.4.gem
/usr/lib64/ruby/gems/2.3.0/gems/sass-rails-5.0.4/MIT-LICENSE
/usr/lib64/ruby/gems/2.3.0/gems/sass-rails-5.0.4/README.md
/usr/lib64/ruby/gems/2.3.0/gems/sass-rails-5.0.4/lib/rails/generators/sass/assets/assets_generator.rb
/usr/lib64/ruby/gems/2.3.0/gems/sass-rails-5.0.4/lib/rails/generators/sass/assets/templates/stylesheet.sass
/usr/lib64/ruby/gems/2.3.0/gems/sass-rails-5.0.4/lib/rails/generators/sass/scaffold/scaffold_generator.rb
/usr/lib64/ruby/gems/2.3.0/gems/sass-rails-5.0.4/lib/rails/generators/sass_scaffold.rb
/usr/lib64/ruby/gems/2.3.0/gems/sass-rails-5.0.4/lib/rails/generators/scss/assets/assets_generator.rb
/usr/lib64/ruby/gems/2.3.0/gems/sass-rails-5.0.4/lib/rails/generators/scss/assets/templates/stylesheet.scss
/usr/lib64/ruby/gems/2.3.0/gems/sass-rails-5.0.4/lib/rails/generators/scss/scaffold/scaffold_generator.rb
/usr/lib64/ruby/gems/2.3.0/gems/sass-rails-5.0.4/lib/sass-rails.rb
/usr/lib64/ruby/gems/2.3.0/gems/sass-rails-5.0.4/lib/sass/rails.rb
/usr/lib64/ruby/gems/2.3.0/gems/sass-rails-5.0.4/lib/sass/rails/cache_store.rb
/usr/lib64/ruby/gems/2.3.0/gems/sass-rails-5.0.4/lib/sass/rails/helpers.rb
/usr/lib64/ruby/gems/2.3.0/gems/sass-rails-5.0.4/lib/sass/rails/importer.rb
/usr/lib64/ruby/gems/2.3.0/gems/sass-rails-5.0.4/lib/sass/rails/logger.rb
/usr/lib64/ruby/gems/2.3.0/gems/sass-rails-5.0.4/lib/sass/rails/railtie.rb
/usr/lib64/ruby/gems/2.3.0/gems/sass-rails-5.0.4/lib/sass/rails/template.rb
/usr/lib64/ruby/gems/2.3.0/gems/sass-rails-5.0.4/lib/sass/rails/version.rb
/usr/lib64/ruby/gems/2.3.0/specifications/sass-rails-5.0.4.gemspec
