#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : rubygem-sass-rails
Version  : 5.0.3
Release  : 1
URL      : https://rubygems.org/downloads/sass-rails-5.0.3.gem
Source0  : https://rubygems.org/downloads/sass-rails-5.0.3.gem
Summary  : No detailed summary available
Group    : Development/Tools
License  : MIT
BuildRequires : ruby
BuildRequires : rubygem-rdoc
BuildRequires : rubygem-sqlite3

%description
# Official Ruby-on-Rails Integration with Sass
This gem provides official integration for Ruby on Rails projects with the Sass stylesheet language.

%prep
gem unpack %{SOURCE0}
%setup -q -D -T -n sass-rails-5.0.3
gem spec %{SOURCE0} -l --ruby > rubygem-sass-rails.gemspec

%build
gem build rubygem-sass-rails.gemspec

%install
%global gem_dir $(ruby -e'puts Gem.default_dir')
gem install -V \
--local \
--force \
--install-dir .%{gem_dir} \
--bindir .%{_bindir} \
sass-rails-5.0.3.gem

mkdir -p %{buildroot}%{gem_dir}
cp -pa .%{gem_dir}/* \
%{buildroot}%{gem_dir}

if [ -d .%{_bindir} ]; then
mkdir -p %{buildroot}%{_bindir}
cp -pa .%{_bindir}/* \
%{buildroot}%{_bindir}/
fi


%files
%defattr(-,root,root,-)
/usr/lib64/ruby/gems/2.2.0/cache/sass-rails-5.0.3.gem
/usr/lib64/ruby/gems/2.2.0/doc/sass-rails-5.0.3/ri/Sass/Generators/AssetsGenerator/cdesc-AssetsGenerator.ri
/usr/lib64/ruby/gems/2.2.0/doc/sass-rails-5.0.3/ri/Sass/Generators/AssetsGenerator/copy_sass-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/sass-rails-5.0.3/ri/Sass/Generators/ScaffoldBase/cdesc-ScaffoldBase.ri
/usr/lib64/ruby/gems/2.2.0/doc/sass-rails-5.0.3/ri/Sass/Generators/ScaffoldBase/copy_stylesheet-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/sass-rails-5.0.3/ri/Sass/Generators/ScaffoldGenerator/cdesc-ScaffoldGenerator.ri
/usr/lib64/ruby/gems/2.2.0/doc/sass-rails-5.0.3/ri/Sass/Generators/ScaffoldGenerator/syntax-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/sass-rails-5.0.3/ri/Sass/Generators/cdesc-Generators.ri
/usr/lib64/ruby/gems/2.2.0/doc/sass-rails-5.0.3/ri/Sass/Plugin/cdesc-Plugin.ri
/usr/lib64/ruby/gems/2.2.0/doc/sass-rails-5.0.3/ri/Sass/Rails/CacheStore/_retrieve-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/sass-rails-5.0.3/ri/Sass/Rails/CacheStore/_store-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/sass-rails-5.0.3/ri/Sass/Rails/CacheStore/cdesc-CacheStore.ri
/usr/lib64/ruby/gems/2.2.0/doc/sass-rails-5.0.3/ri/Sass/Rails/CacheStore/environment-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/sass-rails-5.0.3/ri/Sass/Rails/CacheStore/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/sass-rails-5.0.3/ri/Sass/Rails/CacheStore/path_to-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/sass-rails-5.0.3/ri/Sass/Rails/Logger/_log-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/sass-rails-5.0.3/ri/Sass/Rails/Logger/cdesc-Logger.ri
/usr/lib64/ruby/gems/2.2.0/doc/sass-rails-5.0.3/ri/Sass/Rails/Railtie/ActiveSupport/cdesc-ActiveSupport.ri
/usr/lib64/ruby/gems/2.2.0/doc/sass-rails-5.0.3/ri/Sass/Rails/Railtie/cdesc-Railtie.ri
/usr/lib64/ruby/gems/2.2.0/doc/sass-rails-5.0.3/ri/Sass/Rails/SassImporter/Deprecated/cdesc-Deprecated.ri
/usr/lib64/ruby/gems/2.2.0/doc/sass-rails-5.0.3/ri/Sass/Rails/SassImporter/Deprecated/deprecate_extra_css_extension-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/sass-rails-5.0.3/ri/Sass/Rails/SassImporter/Deprecated/extensions-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/sass-rails-5.0.3/ri/Sass/Rails/SassImporter/Deprecated/find-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/sass-rails-5.0.3/ri/Sass/Rails/SassImporter/Deprecated/find_relative-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/sass-rails-5.0.3/ri/Sass/Rails/SassImporter/ERB/cdesc-ERB.ri
/usr/lib64/ruby/gems/2.2.0/doc/sass-rails-5.0.3/ri/Sass/Rails/SassImporter/ERB/erb_extensions-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/sass-rails-5.0.3/ri/Sass/Rails/SassImporter/ERB/extensions-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/sass-rails-5.0.3/ri/Sass/Rails/SassImporter/ERB/find-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/sass-rails-5.0.3/ri/Sass/Rails/SassImporter/ERB/find_relative-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/sass-rails-5.0.3/ri/Sass/Rails/SassImporter/ERB/process_erb_engine-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/sass-rails-5.0.3/ri/Sass/Rails/SassImporter/Globbing/cdesc-Globbing.ri
/usr/lib64/ruby/gems/2.2.0/doc/sass-rails-5.0.3/ri/Sass/Rails/SassImporter/Globbing/each_globbed_file-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/sass-rails-5.0.3/ri/Sass/Rails/SassImporter/Globbing/find-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/sass-rails-5.0.3/ri/Sass/Rails/SassImporter/Globbing/find_relative-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/sass-rails-5.0.3/ri/Sass/Rails/SassImporter/Globbing/glob_imports-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/sass-rails-5.0.3/ri/Sass/Rails/SassImporter/cdesc-SassImporter.ri
/usr/lib64/ruby/gems/2.2.0/doc/sass-rails-5.0.3/ri/Sass/Rails/SassImporter/extensions-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/sass-rails-5.0.3/ri/Sass/Rails/SassTemplate/cdesc-SassTemplate.ri
/usr/lib64/ruby/gems/2.2.0/doc/sass-rails-5.0.3/ri/Sass/Rails/SassTemplate/default_mime_type-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/sass-rails-5.0.3/ri/Sass/Rails/SassTemplate/engine_initialized%3f-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/sass-rails-5.0.3/ri/Sass/Rails/SassTemplate/evaluate-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/sass-rails-5.0.3/ri/Sass/Rails/SassTemplate/importer_class-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/sass-rails-5.0.3/ri/Sass/Rails/SassTemplate/initialize_engine-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/sass-rails-5.0.3/ri/Sass/Rails/SassTemplate/prepare-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/sass-rails-5.0.3/ri/Sass/Rails/SassTemplate/syntax-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/sass-rails-5.0.3/ri/Sass/Rails/ScssTemplate/cdesc-ScssTemplate.ri
/usr/lib64/ruby/gems/2.2.0/doc/sass-rails-5.0.3/ri/Sass/Rails/ScssTemplate/syntax-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/sass-rails-5.0.3/ri/Sass/Rails/cdesc-Rails.ri
/usr/lib64/ruby/gems/2.2.0/doc/sass-rails-5.0.3/ri/Sass/Script/cdesc-Script.ri
/usr/lib64/ruby/gems/2.2.0/doc/sass-rails-5.0.3/ri/Sass/cdesc-Sass.ri
/usr/lib64/ruby/gems/2.2.0/doc/sass-rails-5.0.3/ri/Scss/Generators/AssetsGenerator/cdesc-AssetsGenerator.ri
/usr/lib64/ruby/gems/2.2.0/doc/sass-rails-5.0.3/ri/Scss/Generators/AssetsGenerator/copy_scss-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/sass-rails-5.0.3/ri/Scss/Generators/ScaffoldGenerator/cdesc-ScaffoldGenerator.ri
/usr/lib64/ruby/gems/2.2.0/doc/sass-rails-5.0.3/ri/Scss/Generators/ScaffoldGenerator/syntax-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/sass-rails-5.0.3/ri/Scss/Generators/cdesc-Generators.ri
/usr/lib64/ruby/gems/2.2.0/doc/sass-rails-5.0.3/ri/Scss/cdesc-Scss.ri
/usr/lib64/ruby/gems/2.2.0/doc/sass-rails-5.0.3/ri/Sprockets/SassFunctions/asset_data_url-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/sass-rails-5.0.3/ri/Sprockets/SassFunctions/cdesc-SassFunctions.ri
/usr/lib64/ruby/gems/2.2.0/doc/sass-rails-5.0.3/ri/Sprockets/cdesc-Sprockets.ri
/usr/lib64/ruby/gems/2.2.0/doc/sass-rails-5.0.3/ri/cache.ri
/usr/lib64/ruby/gems/2.2.0/doc/sass-rails-5.0.3/ri/lib/rails/generators/sass/assets/templates/page-stylesheet_sass.ri
/usr/lib64/ruby/gems/2.2.0/doc/sass-rails-5.0.3/ri/lib/rails/generators/scss/assets/templates/page-stylesheet_scss.ri
/usr/lib64/ruby/gems/2.2.0/gems/sass-rails-5.0.3/MIT-LICENSE
/usr/lib64/ruby/gems/2.2.0/gems/sass-rails-5.0.3/README.md
/usr/lib64/ruby/gems/2.2.0/gems/sass-rails-5.0.3/lib/rails/generators/sass/assets/assets_generator.rb
/usr/lib64/ruby/gems/2.2.0/gems/sass-rails-5.0.3/lib/rails/generators/sass/assets/templates/stylesheet.sass
/usr/lib64/ruby/gems/2.2.0/gems/sass-rails-5.0.3/lib/rails/generators/sass/scaffold/scaffold_generator.rb
/usr/lib64/ruby/gems/2.2.0/gems/sass-rails-5.0.3/lib/rails/generators/sass_scaffold.rb
/usr/lib64/ruby/gems/2.2.0/gems/sass-rails-5.0.3/lib/rails/generators/scss/assets/assets_generator.rb
/usr/lib64/ruby/gems/2.2.0/gems/sass-rails-5.0.3/lib/rails/generators/scss/assets/templates/stylesheet.scss
/usr/lib64/ruby/gems/2.2.0/gems/sass-rails-5.0.3/lib/rails/generators/scss/scaffold/scaffold_generator.rb
/usr/lib64/ruby/gems/2.2.0/gems/sass-rails-5.0.3/lib/sass-rails.rb
/usr/lib64/ruby/gems/2.2.0/gems/sass-rails-5.0.3/lib/sass/rails.rb
/usr/lib64/ruby/gems/2.2.0/gems/sass-rails-5.0.3/lib/sass/rails/cache_store.rb
/usr/lib64/ruby/gems/2.2.0/gems/sass-rails-5.0.3/lib/sass/rails/helpers.rb
/usr/lib64/ruby/gems/2.2.0/gems/sass-rails-5.0.3/lib/sass/rails/importer.rb
/usr/lib64/ruby/gems/2.2.0/gems/sass-rails-5.0.3/lib/sass/rails/logger.rb
/usr/lib64/ruby/gems/2.2.0/gems/sass-rails-5.0.3/lib/sass/rails/railtie.rb
/usr/lib64/ruby/gems/2.2.0/gems/sass-rails-5.0.3/lib/sass/rails/template.rb
/usr/lib64/ruby/gems/2.2.0/gems/sass-rails-5.0.3/lib/sass/rails/version.rb
/usr/lib64/ruby/gems/2.2.0/specifications/sass-rails-5.0.3.gemspec
